[package]
name = "aether_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
flutter_rust_bridge = { version = "=2.3.0", features = ["uuid"] }
uuid = { version = "1.10", features = ["v4"] }
aether_core = { path = "../aether_core" }
aether_render = { path = "../aether_render" }
aether_media = { path = "../aether_media" }

[lib]
crate-type = ["cdylib", "staticlib"]
