// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<void> initEngine() => RustLib.instance.api.crateApiInitEngine();

Future<Timeline> createTimeline() =>
    RustLib.instance.api.crateApiCreateTimeline();

Future<Timeline> addTrack(
        {required Timeline timeline, required TrackKind kind}) =>
    RustLib.instance.api.crateApiAddTrack(timeline: timeline, kind: kind);

Future<Timeline> addClipToTrack(
        {required Timeline timeline,
        required UuidValue trackId,
        required UuidValue sourceId,
        required PlatformInt64 sourceIn,
        required PlatformInt64 sourceOut,
        required PlatformInt64 timelineIn}) =>
    RustLib.instance.api.crateApiAddClipToTrack(
        timeline: timeline,
        trackId: trackId,
        sourceId: sourceId,
        sourceIn: sourceIn,
        sourceOut: sourceOut,
        timelineIn: timelineIn);

class Clip {
  final UuidValue id;
  final UuidValue sourceId;
  final PlatformInt64 sourceIn;
  final PlatformInt64 sourceOut;
  final PlatformInt64 timelineIn;
  final PlatformInt64 timelineOut;

  const Clip({
    required this.id,
    required this.sourceId,
    required this.sourceIn,
    required this.sourceOut,
    required this.timelineIn,
    required this.timelineOut,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      sourceIn.hashCode ^
      sourceOut.hashCode ^
      timelineIn.hashCode ^
      timelineOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Clip &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          sourceIn == other.sourceIn &&
          sourceOut == other.sourceOut &&
          timelineIn == other.timelineIn &&
          timelineOut == other.timelineOut;
}

class Rational {
  final int num;
  final int den;

  const Rational({
    required this.num,
    required this.den,
  });

  @override
  int get hashCode => num.hashCode ^ den.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rational &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          den == other.den;
}

class Timeline {
  final UuidValue id;
  final Rational timebase;
  final PlatformInt64 durationPts;
  final List<Track> tracks;

  const Timeline({
    required this.id,
    required this.timebase,
    required this.durationPts,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^ timebase.hashCode ^ durationPts.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Timeline &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timebase == other.timebase &&
          durationPts == other.durationPts &&
          tracks == other.tracks;
}

class Track {
  final UuidValue id;
  final TrackKind kind;
  final List<Clip> clips;

  const Track({
    required this.id,
    required this.kind,
    required this.clips,
  });

  @override
  int get hashCode => id.hashCode ^ kind.hashCode ^ clips.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          clips == other.clips;
}

enum TrackKind {
  video,
  audio,
  overlay,
  ;
}
