// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

Future<void> initEngine() => RustLib.instance.api.crateApiInitEngine();

Future<Project> createProject(
        {required String name, required String baseDir}) =>
    RustLib.instance.api.crateApiCreateProject(name: name, baseDir: baseDir);

Future<Project> loadProject({required String filePath}) =>
    RustLib.instance.api.crateApiLoadProject(filePath: filePath);

Future<void> saveProject({required Project project}) =>
    RustLib.instance.api.crateApiSaveProject(project: project);

Future<Timeline> createTimeline() =>
    RustLib.instance.api.crateApiCreateTimeline();

Future<Timeline> addTrack(
        {required Timeline timeline, required TrackKind kind}) =>
    RustLib.instance.api.crateApiAddTrack(timeline: timeline, kind: kind);

Future<Timeline> addClipToTrack(
        {required Timeline timeline,
        required UuidValue trackId,
        required UuidValue sourceId,
        required int sourceIn,
        required int sourceOut,
        required int timelineIn}) =>
    RustLib.instance.api.crateApiAddClipToTrack(
        timeline: timeline,
        trackId: trackId,
        sourceId: sourceId,
        sourceIn: sourceIn,
        sourceOut: sourceOut,
        timelineIn: timelineIn);

/// Imports a media file, extracting its type and metadata via `aether_media`.
/// If `project_path` is provided, the imported media is appended to the project's
/// MediaPool and persisted to disk.
Future<MediaItem> importMediaFile(
        {String? projectPath, required String filePath}) =>
    RustLib.instance.api
        .crateApiImportMediaFile(projectPath: projectPath, filePath: filePath);

/// Standalone inspection of a media file without touching project persistence.
Future<MediaItem> inspectMediaFile({required String filePath}) =>
    RustLib.instance.api.crateApiInspectMediaFile(filePath: filePath);

/// Returns the list of imported media items in the specified project.
Future<List<MediaItem>> getMediaItems({required String projectPath}) =>
    RustLib.instance.api.crateApiGetMediaItems(projectPath: projectPath);

/// Returns the entire `MediaPool` structure for the specified project.
Future<MediaPool> getMediaPool({required String projectPath}) =>
    RustLib.instance.api.crateApiGetMediaPool(projectPath: projectPath);

/// Adds a clip referencing a media item's UUID to a specific track in the timeline.
/// Defaults `source_in` to 0, `source_out` to media duration (or 300 PTS for images),
/// and `timeline_in` to the timeline's current duration PTS (append).
Future<Timeline> addClipToTrackFromMedia(
        {required Timeline timeline,
        required UuidValue trackId,
        required MediaItem mediaItem,
        int? sourceIn,
        int? sourceOut,
        int? timelineIn}) =>
    RustLib.instance.api.crateApiAddClipToTrackFromMedia(
        timeline: timeline,
        trackId: trackId,
        mediaItem: mediaItem,
        sourceIn: sourceIn,
        sourceOut: sourceOut,
        timelineIn: timelineIn);

/// Adds a clip referencing a media asset in the project's MediaPool to the project's timeline
/// and persists the project to disk.
Future<Project> addClipFromMediaPool(
        {required Project project,
        required UuidValue trackId,
        required UuidValue mediaId,
        int? sourceIn,
        int? sourceOut,
        int? timelineIn}) =>
    RustLib.instance.api.crateApiAddClipFromMediaPool(
        project: project,
        trackId: trackId,
        mediaId: mediaId,
        sourceIn: sourceIn,
        sourceOut: sourceOut,
        timelineIn: timelineIn);

/// Opens a media asset, extracts container metadata, pre-fetches the initial frame at PTS 0,
/// allocates a unique texture ID for Flutter's `Texture(textureId: ...)` widget,
/// and registers the active playback session in the `SessionRegistry`.
Future<PreviewSessionInfo> createPreviewSession({required String filePath}) =>
    RustLib.instance.api.crateApiCreatePreviewSession(filePath: filePath);

/// Closes the active playback session, terminates background ticker threads,
/// drops active stream sinks, and frees all decoder memory.
Future<void> closePreviewSession({required String sessionId}) =>
    RustLib.instance.api.crateApiClosePreviewSession(sessionId: sessionId);

/// Starts sequential playback at the media asset's native frame rate.
Future<void> previewPlay({required String sessionId}) =>
    RustLib.instance.api.crateApiPreviewPlay(sessionId: sessionId);

/// Pauses sequential playback.
Future<void> previewPause({required String sessionId}) =>
    RustLib.instance.api.crateApiPreviewPause(sessionId: sessionId);

/// Seeks to a specific presentation timestamp (PTS).
/// Clamps out-of-range targets to [0, duration_pts].
/// Decodes and returns the frame at that position immediately for zero-latency scrubber response,
/// while simultaneously broadcasting to any active frame and state stream sinks.
Future<BridgeFrame?> previewSeekPts(
        {required String sessionId, required int targetPts}) =>
    RustLib.instance.api
        .crateApiPreviewSeekPts(sessionId: sessionId, targetPts: targetPts);

/// Convenience seeking jumping to target fractional seconds.
Future<BridgeFrame?> previewSeekSeconds(
        {required String sessionId, required double seconds}) =>
    RustLib.instance.api
        .crateApiPreviewSeekSeconds(sessionId: sessionId, seconds: seconds);

/// Returns the current playback position and playing state.
Future<PlaybackState> getPreviewState({required String sessionId}) =>
    RustLib.instance.api.crateApiGetPreviewState(sessionId: sessionId);

/// Attaches a `StreamSink` to receive continuous RGBA8 video frames as they are decoded.
/// Emits the cached initial frame immediately upon subscription.
Stream<BridgeFrame> subscribePreviewFrames({required String sessionId}) =>
    RustLib.instance.api.crateApiSubscribePreviewFrames(sessionId: sessionId);

/// Attaches a `StreamSink` to receive reactive playback state updates and PTS position ticks.
/// Emits current playback state immediately upon subscription.
Stream<PlaybackState> subscribePlaybackState({required String sessionId}) =>
    RustLib.instance.api.crateApiSubscribePlaybackState(sessionId: sessionId);

/// Stateless thumbnail and scrub extractor: decodes a single frame at PTS without
/// maintaining a persistent playback session.
Future<BridgeFrame> extractSingleFrame(
        {required String filePath, required int targetPts}) =>
    RustLib.instance.api
        .crateApiExtractSingleFrame(filePath: filePath, targetPts: targetPts);

/// Raw RGBA8 video frame transferred across the FFI boundary to Flutter.
class BridgeFrame {
  final int width;
  final int height;
  final int pts;
  final int durationPts;
  final Uint8List rgbaBytes;
  final int rowStrideBytes;
  final double timestampSeconds;

  const BridgeFrame({
    required this.width,
    required this.height,
    required this.pts,
    required this.durationPts,
    required this.rgbaBytes,
    required this.rowStrideBytes,
    required this.timestampSeconds,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      pts.hashCode ^
      durationPts.hashCode ^
      rgbaBytes.hashCode ^
      rowStrideBytes.hashCode ^
      timestampSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          pts == other.pts &&
          durationPts == other.durationPts &&
          rgbaBytes == other.rgbaBytes &&
          rowStrideBytes == other.rowStrideBytes &&
          timestampSeconds == other.timestampSeconds;
}

class Clip {
  final UuidValue id;
  final UuidValue sourceId;
  final int sourceIn;
  final int sourceOut;
  final int timelineIn;
  final int timelineOut;

  const Clip({
    required this.id,
    required this.sourceId,
    required this.sourceIn,
    required this.sourceOut,
    required this.timelineIn,
    required this.timelineOut,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      sourceIn.hashCode ^
      sourceOut.hashCode ^
      timelineIn.hashCode ^
      timelineOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Clip &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          sourceIn == other.sourceIn &&
          sourceOut == other.sourceOut &&
          timelineIn == other.timelineIn &&
          timelineOut == other.timelineOut;
}

class MediaItem {
  final UuidValue id;
  final String filePath;
  final String fileName;
  final MediaType mediaType;
  final MediaMetadata metadata;

  const MediaItem({
    required this.id,
    required this.filePath,
    required this.fileName,
    required this.mediaType,
    required this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      filePath.hashCode ^
      fileName.hashCode ^
      mediaType.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filePath == other.filePath &&
          fileName == other.fileName &&
          mediaType == other.mediaType &&
          metadata == other.metadata;
}

class MediaMetadata {
  final int? width;
  final int? height;
  final int durationPts;
  final double durationSeconds;
  final Rational? timebase;
  final int? audioChannels;
  final int? sampleRate;
  final int fileSizeBytes;
  final String? videoCodec;
  final String? audioCodec;
  final String? pixelFormat;
  final bool? isVfr;
  final List<int>? keyframePts;

  const MediaMetadata({
    this.width,
    this.height,
    required this.durationPts,
    required this.durationSeconds,
    this.timebase,
    this.audioChannels,
    this.sampleRate,
    required this.fileSizeBytes,
    this.videoCodec,
    this.audioCodec,
    this.pixelFormat,
    this.isVfr,
    this.keyframePts,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      durationPts.hashCode ^
      durationSeconds.hashCode ^
      timebase.hashCode ^
      audioChannels.hashCode ^
      sampleRate.hashCode ^
      fileSizeBytes.hashCode ^
      videoCodec.hashCode ^
      audioCodec.hashCode ^
      pixelFormat.hashCode ^
      isVfr.hashCode ^
      keyframePts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaMetadata &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          durationPts == other.durationPts &&
          durationSeconds == other.durationSeconds &&
          timebase == other.timebase &&
          audioChannels == other.audioChannels &&
          sampleRate == other.sampleRate &&
          fileSizeBytes == other.fileSizeBytes &&
          videoCodec == other.videoCodec &&
          audioCodec == other.audioCodec &&
          pixelFormat == other.pixelFormat &&
          isVfr == other.isVfr &&
          keyframePts == other.keyframePts;
}

class MediaPool {
  final List<MediaItem> items;

  const MediaPool({
    required this.items,
  });

  @override
  int get hashCode => items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaPool &&
          runtimeType == other.runtimeType &&
          items == other.items;
}

enum MediaType {
  video,
  audio,
  image,
  ;
}

/// Instantaneous playback state snapshot for reactive UI synchronization.
class PlaybackState {
  final String sessionId;
  final bool isPlaying;
  final int currentPts;
  final double currentSeconds;
  final int durationPts;
  final double durationSeconds;

  const PlaybackState({
    required this.sessionId,
    required this.isPlaying,
    required this.currentPts,
    required this.currentSeconds,
    required this.durationPts,
    required this.durationSeconds,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      isPlaying.hashCode ^
      currentPts.hashCode ^
      currentSeconds.hashCode ^
      durationPts.hashCode ^
      durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          isPlaying == other.isPlaying &&
          currentPts == other.currentPts &&
          currentSeconds == other.currentSeconds &&
          durationPts == other.durationPts &&
          durationSeconds == other.durationSeconds;
}

/// Technical metadata and Flutter Texture widget handle for an active preview session.
class PreviewSessionInfo {
  final String sessionId;
  final int textureId;
  final int width;
  final int height;
  final int durationPts;
  final double durationSeconds;
  final double fps;
  final Rational timebase;

  const PreviewSessionInfo({
    required this.sessionId,
    required this.textureId,
    required this.width,
    required this.height,
    required this.durationPts,
    required this.durationSeconds,
    required this.fps,
    required this.timebase,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      textureId.hashCode ^
      width.hashCode ^
      height.hashCode ^
      durationPts.hashCode ^
      durationSeconds.hashCode ^
      fps.hashCode ^
      timebase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewSessionInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          textureId == other.textureId &&
          width == other.width &&
          height == other.height &&
          durationPts == other.durationPts &&
          durationSeconds == other.durationSeconds &&
          fps == other.fps &&
          timebase == other.timebase;
}

class Project {
  final String id;
  final String name;
  final String projectPath;
  final String filePath;
  final Timeline timeline;
  final MediaPool mediaPool;

  const Project({
    required this.id,
    required this.name,
    required this.projectPath,
    required this.filePath,
    required this.timeline,
    required this.mediaPool,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      projectPath.hashCode ^
      filePath.hashCode ^
      timeline.hashCode ^
      mediaPool.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Project &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          projectPath == other.projectPath &&
          filePath == other.filePath &&
          timeline == other.timeline &&
          mediaPool == other.mediaPool;
}

class Rational {
  final int num;
  final int den;

  const Rational({
    required this.num,
    required this.den,
  });

  @override
  int get hashCode => num.hashCode ^ den.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rational &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          den == other.den;
}

class Timeline {
  final UuidValue id;
  final Rational timebase;
  final int durationPts;
  final List<Track> tracks;

  const Timeline({
    required this.id,
    required this.timebase,
    required this.durationPts,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^ timebase.hashCode ^ durationPts.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Timeline &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timebase == other.timebase &&
          durationPts == other.durationPts &&
          tracks == other.tracks;
}

class Track {
  final UuidValue id;
  final TrackKind kind;
  final List<Clip> clips;

  const Track({
    required this.id,
    required this.kind,
    required this.clips,
  });

  @override
  int get hashCode => id.hashCode ^ kind.hashCode ^ clips.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          clips == other.clips;
}

enum TrackKind {
  video,
  audio,
  overlay,
  ;
}
