// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

Future<void> initEngine() => RustLib.instance.api.crateApiInitEngine();

Future<Project> createProject(
        {required String name, required String baseDir}) =>
    RustLib.instance.api.crateApiCreateProject(name: name, baseDir: baseDir);

Future<Project> loadProject({required String filePath}) =>
    RustLib.instance.api.crateApiLoadProject(filePath: filePath);

Future<void> saveProject({required Project project}) =>
    RustLib.instance.api.crateApiSaveProject(project: project);

Future<Timeline> createTimeline() =>
    RustLib.instance.api.crateApiCreateTimeline();

Future<Timeline> addTrack(
        {required Timeline timeline, required TrackKind kind}) =>
    RustLib.instance.api.crateApiAddTrack(timeline: timeline, kind: kind);

Future<Timeline> addClipToTrack(
        {required Timeline timeline,
        required UuidValue trackId,
        required UuidValue sourceId,
        required int sourceIn,
        required int sourceOut,
        required int timelineIn}) =>
    RustLib.instance.api.crateApiAddClipToTrack(
        timeline: timeline,
        trackId: trackId,
        sourceId: sourceId,
        sourceIn: sourceIn,
        sourceOut: sourceOut,
        timelineIn: timelineIn);

class Clip {
  final UuidValue id;
  final UuidValue sourceId;
  final int sourceIn;
  final int sourceOut;
  final int timelineIn;
  final int timelineOut;

  const Clip({
    required this.id,
    required this.sourceId,
    required this.sourceIn,
    required this.sourceOut,
    required this.timelineIn,
    required this.timelineOut,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      sourceIn.hashCode ^
      sourceOut.hashCode ^
      timelineIn.hashCode ^
      timelineOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Clip &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          sourceIn == other.sourceIn &&
          sourceOut == other.sourceOut &&
          timelineIn == other.timelineIn &&
          timelineOut == other.timelineOut;
}

class Project {
  final String id;
  final String name;
  final String projectPath;
  final String filePath;
  final Timeline timeline;

  const Project({
    required this.id,
    required this.name,
    required this.projectPath,
    required this.filePath,
    required this.timeline,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      projectPath.hashCode ^
      filePath.hashCode ^
      timeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Project &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          projectPath == other.projectPath &&
          filePath == other.filePath &&
          timeline == other.timeline;
}

class Rational {
  final int num;
  final int den;

  const Rational({
    required this.num,
    required this.den,
  });

  @override
  int get hashCode => num.hashCode ^ den.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rational &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          den == other.den;
}

class Timeline {
  final UuidValue id;
  final Rational timebase;
  final int durationPts;
  final List<Track> tracks;

  const Timeline({
    required this.id,
    required this.timebase,
    required this.durationPts,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^ timebase.hashCode ^ durationPts.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Timeline &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timebase == other.timebase &&
          durationPts == other.durationPts &&
          tracks == other.tracks;
}

class Track {
  final UuidValue id;
  final TrackKind kind;
  final List<Clip> clips;

  const Track({
    required this.id,
    required this.kind,
    required this.clips,
  });

  @override
  int get hashCode => id.hashCode ^ kind.hashCode ^ clips.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          clips == other.clips;
}

enum TrackKind {
  video,
  audio,
  overlay,
  ;
}
