// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.3.0';

  @override
  int get rustContentHash => -2067963356;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'aether_bridge',
    ioDirectory: '../../crates/aether_bridge/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Timeline> crateApiAddClipToTrack(
      {required Timeline timeline,
      required UuidValue trackId,
      required UuidValue sourceId,
      required int sourceIn,
      required int sourceOut,
      required int timelineIn});

  Future<Timeline> crateApiAddTrack(
      {required Timeline timeline, required TrackKind kind});

  Future<Project> crateApiCreateProject(
      {required String name, required String baseDir});

  Future<Timeline> crateApiCreateTimeline();

  Future<void> crateApiInitEngine();

  Future<Project> crateApiLoadProject({required String filePath});

  Future<void> crateApiSaveProject({required Project project});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Timeline> crateApiAddClipToTrack(
      {required Timeline timeline,
      required UuidValue trackId,
      required UuidValue sourceId,
      required int sourceIn,
      required int sourceOut,
      required int timelineIn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_timeline(timeline, serializer);
        sse_encode_Uuid(trackId, serializer);
        sse_encode_Uuid(sourceId, serializer);
        sse_encode_CastedPrimitive_i_64(sourceIn, serializer);
        sse_encode_CastedPrimitive_i_64(sourceOut, serializer);
        sse_encode_CastedPrimitive_i_64(timelineIn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddClipToTrackConstMeta,
      argValues: [timeline, trackId, sourceId, sourceIn, sourceOut, timelineIn],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddClipToTrackConstMeta => const TaskConstMeta(
        debugName: "add_clip_to_track",
        argNames: [
          "timeline",
          "trackId",
          "sourceId",
          "sourceIn",
          "sourceOut",
          "timelineIn"
        ],
      );

  @override
  Future<Timeline> crateApiAddTrack(
      {required Timeline timeline, required TrackKind kind}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_timeline(timeline, serializer);
        sse_encode_track_kind(kind, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAddTrackConstMeta,
      argValues: [timeline, kind],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddTrackConstMeta => const TaskConstMeta(
        debugName: "add_track",
        argNames: ["timeline", "kind"],
      );

  @override
  Future<Project> crateApiCreateProject(
      {required String name, required String baseDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(baseDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateProjectConstMeta,
      argValues: [name, baseDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateProjectConstMeta => const TaskConstMeta(
        debugName: "create_project",
        argNames: ["name", "baseDir"],
      );

  @override
  Future<Timeline> crateApiCreateTimeline() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCreateTimelineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateTimelineConstMeta => const TaskConstMeta(
        debugName: "create_timeline",
        argNames: [],
      );

  @override
  Future<void> crateApiInitEngine() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitEngineConstMeta => const TaskConstMeta(
        debugName: "init_engine",
        argNames: [],
      );

  @override
  Future<Project> crateApiLoadProject({required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoadProjectConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoadProjectConstMeta => const TaskConstMeta(
        debugName: "load_project",
        argNames: ["filePath"],
      );

  @override
  Future<void> crateApiSaveProject({required Project project}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project(project, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveProjectConstMeta,
      argValues: [project],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveProjectConstMeta => const TaskConstMeta(
        debugName: "save_project",
        argNames: ["project"],
      );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
        'Not implemented in this codec, please use the other one');
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  Project dco_decode_box_autoadd_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_project(raw);
  }

  @protected
  Timeline dco_decode_box_autoadd_timeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_timeline(raw);
  }

  @protected
  Clip dco_decode_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Clip(
      id: dco_decode_Uuid(arr[0]),
      sourceId: dco_decode_Uuid(arr[1]),
      sourceIn: dco_decode_CastedPrimitive_i_64(arr[2]),
      sourceOut: dco_decode_CastedPrimitive_i_64(arr[3]),
      timelineIn: dco_decode_CastedPrimitive_i_64(arr[4]),
      timelineOut: dco_decode_CastedPrimitive_i_64(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Clip> dco_decode_list_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_clip).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  Project dco_decode_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Project(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      projectPath: dco_decode_String(arr[2]),
      filePath: dco_decode_String(arr[3]),
      timeline: dco_decode_timeline(arr[4]),
    );
  }

  @protected
  Rational dco_decode_rational(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Rational(
      num: dco_decode_i_32(arr[0]),
      den: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  Timeline dco_decode_timeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Timeline(
      id: dco_decode_Uuid(arr[0]),
      timebase: dco_decode_rational(arr[1]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[2]),
      tracks: dco_decode_list_track(arr[3]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Track(
      id: dco_decode_Uuid(arr[0]),
      kind: dco_decode_track_kind(arr[1]),
      clips: dco_decode_list_clip(arr[2]),
    );
  }

  @protected
  TrackKind dco_decode_track_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrackKind.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  Project sse_decode_box_autoadd_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_project(deserializer));
  }

  @protected
  Timeline sse_decode_box_autoadd_timeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_timeline(deserializer));
  }

  @protected
  Clip sse_decode_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_sourceId = sse_decode_Uuid(deserializer);
    var var_sourceIn = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_sourceOut = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_timelineIn = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_timelineOut = sse_decode_CastedPrimitive_i_64(deserializer);
    return Clip(
        id: var_id,
        sourceId: var_sourceId,
        sourceIn: var_sourceIn,
        sourceOut: var_sourceOut,
        timelineIn: var_timelineIn,
        timelineOut: var_timelineOut);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Clip> sse_decode_list_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Clip>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_clip(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  Project sse_decode_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_projectPath = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_timeline = sse_decode_timeline(deserializer);
    return Project(
        id: var_id,
        name: var_name,
        projectPath: var_projectPath,
        filePath: var_filePath,
        timeline: var_timeline);
  }

  @protected
  Rational sse_decode_rational(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_num = sse_decode_i_32(deserializer);
    var var_den = sse_decode_i_32(deserializer);
    return Rational(num: var_num, den: var_den);
  }

  @protected
  Timeline sse_decode_timeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_timebase = sse_decode_rational(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_tracks = sse_decode_list_track(deserializer);
    return Timeline(
        id: var_id,
        timebase: var_timebase,
        durationPts: var_durationPts,
        tracks: var_tracks);
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_kind = sse_decode_track_kind(deserializer);
    var var_clips = sse_decode_list_clip(deserializer);
    return Track(id: var_id, kind: var_kind, clips: var_clips);
  }

  @protected
  TrackKind sse_decode_track_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrackKind.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_box_autoadd_project(Project self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_timeline(
      Timeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_timeline(self, serializer);
  }

  @protected
  void sse_encode_clip(Clip self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_Uuid(self.sourceId, serializer);
    sse_encode_CastedPrimitive_i_64(self.sourceIn, serializer);
    sse_encode_CastedPrimitive_i_64(self.sourceOut, serializer);
    sse_encode_CastedPrimitive_i_64(self.timelineIn, serializer);
    sse_encode_CastedPrimitive_i_64(self.timelineOut, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_clip(List<Clip> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_clip(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_project(Project self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.projectPath, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_timeline(self.timeline, serializer);
  }

  @protected
  void sse_encode_rational(Rational self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.num, serializer);
    sse_encode_i_32(self.den, serializer);
  }

  @protected
  void sse_encode_timeline(Timeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_rational(self.timebase, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_list_track(self.tracks, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_track_kind(self.kind, serializer);
    sse_encode_list_clip(self.clips, serializer);
  }

  @protected
  void sse_encode_track_kind(TrackKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
