// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  Project dco_decode_box_autoadd_project(dynamic raw);

  @protected
  Timeline dco_decode_box_autoadd_timeline(dynamic raw);

  @protected
  Clip dco_decode_clip(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Clip> dco_decode_list_clip(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Track> dco_decode_list_track(dynamic raw);

  @protected
  Project dco_decode_project(dynamic raw);

  @protected
  Rational dco_decode_rational(dynamic raw);

  @protected
  Timeline dco_decode_timeline(dynamic raw);

  @protected
  Track dco_decode_track(dynamic raw);

  @protected
  TrackKind dco_decode_track_kind(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  Project sse_decode_box_autoadd_project(SseDeserializer deserializer);

  @protected
  Timeline sse_decode_box_autoadd_timeline(SseDeserializer deserializer);

  @protected
  Clip sse_decode_clip(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Clip> sse_decode_list_clip(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer);

  @protected
  Project sse_decode_project(SseDeserializer deserializer);

  @protected
  Rational sse_decode_rational(SseDeserializer deserializer);

  @protected
  Timeline sse_decode_timeline(SseDeserializer deserializer);

  @protected
  Track sse_decode_track(SseDeserializer deserializer);

  @protected
  TrackKind sse_decode_track_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_project(Project self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_timeline(Timeline self, SseSerializer serializer);

  @protected
  void sse_encode_clip(Clip self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_clip(List<Clip> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer);

  @protected
  void sse_encode_project(Project self, SseSerializer serializer);

  @protected
  void sse_encode_rational(Rational self, SseSerializer serializer);

  @protected
  void sse_encode_timeline(Timeline self, SseSerializer serializer);

  @protected
  void sse_encode_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_track_kind(TrackKind self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
