// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.3.0';

  @override
  int get rustContentHash => 738719927;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'aether_bridge',
    ioDirectory: '../../crates/aether_bridge/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Project> crateApiAddClipFromMediaPool(
      {required Project project,
      required UuidValue trackId,
      required UuidValue mediaId,
      int? sourceIn,
      int? sourceOut,
      int? timelineIn});

  Future<Timeline> crateApiAddClipToTrack(
      {required Timeline timeline,
      required UuidValue trackId,
      required UuidValue sourceId,
      required int sourceIn,
      required int sourceOut,
      required int timelineIn});

  Future<Timeline> crateApiAddClipToTrackFromMedia(
      {required Timeline timeline,
      required UuidValue trackId,
      required MediaItem mediaItem,
      int? sourceIn,
      int? sourceOut,
      int? timelineIn});

  Future<Timeline> crateApiAddTrack(
      {required Timeline timeline, required TrackKind kind});

  Future<void> crateApiClosePreviewSession({required String sessionId});

  Future<PreviewSessionInfo> crateApiCreatePreviewSession(
      {required String filePath});

  Future<Project> crateApiCreateProject(
      {required String name, required String baseDir});

  Future<Timeline> crateApiCreateTimeline();

  Future<BridgeFrame> crateApiExtractSingleFrame(
      {required String filePath, required int targetPts});

  Future<List<MediaItem>> crateApiGetMediaItems({required String projectPath});

  Future<MediaPool> crateApiGetMediaPool({required String projectPath});

  Future<PlaybackState> crateApiGetPreviewState({required String sessionId});

  Future<MediaItem> crateApiImportMediaFile(
      {String? projectPath, required String filePath});

  Future<void> crateApiInitEngine();

  Future<MediaItem> crateApiInspectMediaFile({required String filePath});

  Future<Project> crateApiLoadProject({required String filePath});

  Future<void> crateApiPreviewPause({required String sessionId});

  Future<void> crateApiPreviewPlay({required String sessionId});

  Future<BridgeFrame?> crateApiPreviewSeekPts(
      {required String sessionId, required int targetPts});

  Future<BridgeFrame?> crateApiPreviewSeekSeconds(
      {required String sessionId, required double seconds});

  Future<void> crateApiSaveProject({required Project project});

  Stream<PlaybackState> crateApiSubscribePlaybackState(
      {required String sessionId});

  Stream<BridgeFrame> crateApiSubscribePreviewFrames(
      {required String sessionId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Project> crateApiAddClipFromMediaPool(
      {required Project project,
      required UuidValue trackId,
      required UuidValue mediaId,
      int? sourceIn,
      int? sourceOut,
      int? timelineIn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project(project, serializer);
        sse_encode_Uuid(trackId, serializer);
        sse_encode_Uuid(mediaId, serializer);
        sse_encode_opt_CastedPrimitive_i_64(sourceIn, serializer);
        sse_encode_opt_CastedPrimitive_i_64(sourceOut, serializer);
        sse_encode_opt_CastedPrimitive_i_64(timelineIn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddClipFromMediaPoolConstMeta,
      argValues: [project, trackId, mediaId, sourceIn, sourceOut, timelineIn],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddClipFromMediaPoolConstMeta =>
      const TaskConstMeta(
        debugName: "add_clip_from_media_pool",
        argNames: [
          "project",
          "trackId",
          "mediaId",
          "sourceIn",
          "sourceOut",
          "timelineIn"
        ],
      );

  @override
  Future<Timeline> crateApiAddClipToTrack(
      {required Timeline timeline,
      required UuidValue trackId,
      required UuidValue sourceId,
      required int sourceIn,
      required int sourceOut,
      required int timelineIn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_timeline(timeline, serializer);
        sse_encode_Uuid(trackId, serializer);
        sse_encode_Uuid(sourceId, serializer);
        sse_encode_CastedPrimitive_i_64(sourceIn, serializer);
        sse_encode_CastedPrimitive_i_64(sourceOut, serializer);
        sse_encode_CastedPrimitive_i_64(timelineIn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddClipToTrackConstMeta,
      argValues: [timeline, trackId, sourceId, sourceIn, sourceOut, timelineIn],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddClipToTrackConstMeta => const TaskConstMeta(
        debugName: "add_clip_to_track",
        argNames: [
          "timeline",
          "trackId",
          "sourceId",
          "sourceIn",
          "sourceOut",
          "timelineIn"
        ],
      );

  @override
  Future<Timeline> crateApiAddClipToTrackFromMedia(
      {required Timeline timeline,
      required UuidValue trackId,
      required MediaItem mediaItem,
      int? sourceIn,
      int? sourceOut,
      int? timelineIn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_timeline(timeline, serializer);
        sse_encode_Uuid(trackId, serializer);
        sse_encode_box_autoadd_media_item(mediaItem, serializer);
        sse_encode_opt_CastedPrimitive_i_64(sourceIn, serializer);
        sse_encode_opt_CastedPrimitive_i_64(sourceOut, serializer);
        sse_encode_opt_CastedPrimitive_i_64(timelineIn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddClipToTrackFromMediaConstMeta,
      argValues: [
        timeline,
        trackId,
        mediaItem,
        sourceIn,
        sourceOut,
        timelineIn
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddClipToTrackFromMediaConstMeta =>
      const TaskConstMeta(
        debugName: "add_clip_to_track_from_media",
        argNames: [
          "timeline",
          "trackId",
          "mediaItem",
          "sourceIn",
          "sourceOut",
          "timelineIn"
        ],
      );

  @override
  Future<Timeline> crateApiAddTrack(
      {required Timeline timeline, required TrackKind kind}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_timeline(timeline, serializer);
        sse_encode_track_kind(kind, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAddTrackConstMeta,
      argValues: [timeline, kind],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddTrackConstMeta => const TaskConstMeta(
        debugName: "add_track",
        argNames: ["timeline", "kind"],
      );

  @override
  Future<void> crateApiClosePreviewSession({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiClosePreviewSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClosePreviewSessionConstMeta =>
      const TaskConstMeta(
        debugName: "close_preview_session",
        argNames: ["sessionId"],
      );

  @override
  Future<PreviewSessionInfo> crateApiCreatePreviewSession(
      {required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_preview_session_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreatePreviewSessionConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreatePreviewSessionConstMeta =>
      const TaskConstMeta(
        debugName: "create_preview_session",
        argNames: ["filePath"],
      );

  @override
  Future<Project> crateApiCreateProject(
      {required String name, required String baseDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(baseDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateProjectConstMeta,
      argValues: [name, baseDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateProjectConstMeta => const TaskConstMeta(
        debugName: "create_project",
        argNames: ["name", "baseDir"],
      );

  @override
  Future<Timeline> crateApiCreateTimeline() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_timeline,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCreateTimelineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateTimelineConstMeta => const TaskConstMeta(
        debugName: "create_timeline",
        argNames: [],
      );

  @override
  Future<BridgeFrame> crateApiExtractSingleFrame(
      {required String filePath, required int targetPts}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        sse_encode_CastedPrimitive_i_64(targetPts, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_frame,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExtractSingleFrameConstMeta,
      argValues: [filePath, targetPts],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExtractSingleFrameConstMeta => const TaskConstMeta(
        debugName: "extract_single_frame",
        argNames: ["filePath", "targetPts"],
      );

  @override
  Future<List<MediaItem>> crateApiGetMediaItems({required String projectPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_media_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetMediaItemsConstMeta,
      argValues: [projectPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetMediaItemsConstMeta => const TaskConstMeta(
        debugName: "get_media_items",
        argNames: ["projectPath"],
      );

  @override
  Future<MediaPool> crateApiGetMediaPool({required String projectPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_pool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetMediaPoolConstMeta,
      argValues: [projectPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetMediaPoolConstMeta => const TaskConstMeta(
        debugName: "get_media_pool",
        argNames: ["projectPath"],
      );

  @override
  Future<PlaybackState> crateApiGetPreviewState({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_playback_state,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetPreviewStateConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetPreviewStateConstMeta => const TaskConstMeta(
        debugName: "get_preview_state",
        argNames: ["sessionId"],
      );

  @override
  Future<MediaItem> crateApiImportMediaFile(
      {String? projectPath, required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(projectPath, serializer);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImportMediaFileConstMeta,
      argValues: [projectPath, filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportMediaFileConstMeta => const TaskConstMeta(
        debugName: "import_media_file",
        argNames: ["projectPath", "filePath"],
      );

  @override
  Future<void> crateApiInitEngine() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitEngineConstMeta => const TaskConstMeta(
        debugName: "init_engine",
        argNames: [],
      );

  @override
  Future<MediaItem> crateApiInspectMediaFile({required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_media_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInspectMediaFileConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInspectMediaFileConstMeta => const TaskConstMeta(
        debugName: "inspect_media_file",
        argNames: ["filePath"],
      );

  @override
  Future<Project> crateApiLoadProject({required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLoadProjectConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoadProjectConstMeta => const TaskConstMeta(
        debugName: "load_project",
        argNames: ["filePath"],
      );

  @override
  Future<void> crateApiPreviewPause({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPreviewPauseConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPreviewPauseConstMeta => const TaskConstMeta(
        debugName: "preview_pause",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiPreviewPlay({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPreviewPlayConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPreviewPlayConstMeta => const TaskConstMeta(
        debugName: "preview_play",
        argNames: ["sessionId"],
      );

  @override
  Future<BridgeFrame?> crateApiPreviewSeekPts(
      {required String sessionId, required int targetPts}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_CastedPrimitive_i_64(targetPts, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_bridge_frame,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPreviewSeekPtsConstMeta,
      argValues: [sessionId, targetPts],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPreviewSeekPtsConstMeta => const TaskConstMeta(
        debugName: "preview_seek_pts",
        argNames: ["sessionId", "targetPts"],
      );

  @override
  Future<BridgeFrame?> crateApiPreviewSeekSeconds(
      {required String sessionId, required double seconds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_f_64(seconds, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_bridge_frame,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPreviewSeekSecondsConstMeta,
      argValues: [sessionId, seconds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPreviewSeekSecondsConstMeta => const TaskConstMeta(
        debugName: "preview_seek_seconds",
        argNames: ["sessionId", "seconds"],
      );

  @override
  Future<void> crateApiSaveProject({required Project project}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project(project, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveProjectConstMeta,
      argValues: [project],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveProjectConstMeta => const TaskConstMeta(
        debugName: "save_project",
        argNames: ["project"],
      );

  @override
  Stream<PlaybackState> crateApiSubscribePlaybackState(
      {required String sessionId}) {
    final sink = RustStreamSink<PlaybackState>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_StreamSink_playback_state_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSubscribePlaybackStateConstMeta,
      argValues: [sessionId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribePlaybackStateConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_playback_state",
        argNames: ["sessionId", "sink"],
      );

  @override
  Stream<BridgeFrame> crateApiSubscribePreviewFrames(
      {required String sessionId}) {
    final sink = RustStreamSink<BridgeFrame>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_StreamSink_bridge_frame_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSubscribePreviewFramesConstMeta,
      argValues: [sessionId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribePreviewFramesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_preview_frames",
        argNames: ["sessionId", "sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
        'Not implemented in this codec, please use the other one');
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
        'Not implemented in this codec, please use the other one');
  }

  @protected
  RustStreamSink<BridgeFrame> dco_decode_StreamSink_bridge_frame_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PlaybackState> dco_decode_StreamSink_playback_state_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeFrame dco_decode_box_autoadd_bridge_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_frame(raw);
  }

  @protected
  MediaItem dco_decode_box_autoadd_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_item(raw);
  }

  @protected
  Project dco_decode_box_autoadd_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_project(raw);
  }

  @protected
  Rational dco_decode_box_autoadd_rational(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rational(raw);
  }

  @protected
  Timeline dco_decode_box_autoadd_timeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_timeline(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BridgeFrame dco_decode_bridge_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeFrame(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      pts: dco_decode_CastedPrimitive_i_64(arr[2]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[3]),
      rgbaBytes: dco_decode_list_prim_u_8_strict(arr[4]),
      rowStrideBytes: dco_decode_u_32(arr[5]),
      timestampSeconds: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  Clip dco_decode_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Clip(
      id: dco_decode_Uuid(arr[0]),
      sourceId: dco_decode_Uuid(arr[1]),
      sourceIn: dco_decode_CastedPrimitive_i_64(arr[2]),
      sourceOut: dco_decode_CastedPrimitive_i_64(arr[3]),
      timelineIn: dco_decode_CastedPrimitive_i_64(arr[4]),
      timelineOut: dco_decode_CastedPrimitive_i_64(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Clip> dco_decode_list_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_clip).toList();
  }

  @protected
  List<MediaItem> dco_decode_list_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  MediaItem dco_decode_media_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MediaItem(
      id: dco_decode_Uuid(arr[0]),
      filePath: dco_decode_String(arr[1]),
      fileName: dco_decode_String(arr[2]),
      mediaType: dco_decode_media_type(arr[3]),
      metadata: dco_decode_media_metadata(arr[4]),
    );
  }

  @protected
  MediaMetadata dco_decode_media_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MediaMetadata(
      width: dco_decode_opt_box_autoadd_u_32(arr[0]),
      height: dco_decode_opt_box_autoadd_u_32(arr[1]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[2]),
      durationSeconds: dco_decode_f_64(arr[3]),
      timebase: dco_decode_opt_box_autoadd_rational(arr[4]),
      audioChannels: dco_decode_opt_box_autoadd_u_16(arr[5]),
      sampleRate: dco_decode_opt_box_autoadd_u_32(arr[6]),
      fileSizeBytes: dco_decode_CastedPrimitive_u_64(arr[7]),
    );
  }

  @protected
  MediaPool dco_decode_media_pool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return MediaPool(
      items: dco_decode_list_media_item(arr[0]),
    );
  }

  @protected
  MediaType dco_decode_media_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaType.values[raw as int];
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_i_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeFrame? dco_decode_opt_box_autoadd_bridge_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_frame(raw);
  }

  @protected
  Rational? dco_decode_opt_box_autoadd_rational(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rational(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlaybackState(
      sessionId: dco_decode_String(arr[0]),
      isPlaying: dco_decode_bool(arr[1]),
      currentPts: dco_decode_CastedPrimitive_i_64(arr[2]),
      currentSeconds: dco_decode_f_64(arr[3]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[4]),
      durationSeconds: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  PreviewSessionInfo dco_decode_preview_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PreviewSessionInfo(
      sessionId: dco_decode_String(arr[0]),
      textureId: dco_decode_CastedPrimitive_i_64(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[4]),
      durationSeconds: dco_decode_f_64(arr[5]),
      fps: dco_decode_f_64(arr[6]),
      timebase: dco_decode_rational(arr[7]),
    );
  }

  @protected
  Project dco_decode_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Project(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      projectPath: dco_decode_String(arr[2]),
      filePath: dco_decode_String(arr[3]),
      timeline: dco_decode_timeline(arr[4]),
      mediaPool: dco_decode_media_pool(arr[5]),
    );
  }

  @protected
  Rational dco_decode_rational(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Rational(
      num: dco_decode_i_32(arr[0]),
      den: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  Timeline dco_decode_timeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Timeline(
      id: dco_decode_Uuid(arr[0]),
      timebase: dco_decode_rational(arr[1]),
      durationPts: dco_decode_CastedPrimitive_i_64(arr[2]),
      tracks: dco_decode_list_track(arr[3]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Track(
      id: dco_decode_Uuid(arr[0]),
      kind: dco_decode_track_kind(arr[1]),
      clips: dco_decode_list_clip(arr[2]),
    );
  }

  @protected
  TrackKind dco_decode_track_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrackKind.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  RustStreamSink<BridgeFrame> sse_decode_StreamSink_bridge_frame_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PlaybackState> sse_decode_StreamSink_playback_state_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeFrame sse_decode_box_autoadd_bridge_frame(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_frame(deserializer));
  }

  @protected
  MediaItem sse_decode_box_autoadd_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_item(deserializer));
  }

  @protected
  Project sse_decode_box_autoadd_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_project(deserializer));
  }

  @protected
  Rational sse_decode_box_autoadd_rational(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rational(deserializer));
  }

  @protected
  Timeline sse_decode_box_autoadd_timeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_timeline(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BridgeFrame sse_decode_bridge_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_pts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_rgbaBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_rowStrideBytes = sse_decode_u_32(deserializer);
    var var_timestampSeconds = sse_decode_f_64(deserializer);
    return BridgeFrame(
        width: var_width,
        height: var_height,
        pts: var_pts,
        durationPts: var_durationPts,
        rgbaBytes: var_rgbaBytes,
        rowStrideBytes: var_rowStrideBytes,
        timestampSeconds: var_timestampSeconds);
  }

  @protected
  Clip sse_decode_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_sourceId = sse_decode_Uuid(deserializer);
    var var_sourceIn = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_sourceOut = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_timelineIn = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_timelineOut = sse_decode_CastedPrimitive_i_64(deserializer);
    return Clip(
        id: var_id,
        sourceId: var_sourceId,
        sourceIn: var_sourceIn,
        sourceOut: var_sourceOut,
        timelineIn: var_timelineIn,
        timelineOut: var_timelineOut);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Clip> sse_decode_list_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Clip>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_clip(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaItem> sse_decode_list_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  MediaItem sse_decode_media_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_mediaType = sse_decode_media_type(deserializer);
    var var_metadata = sse_decode_media_metadata(deserializer);
    return MediaItem(
        id: var_id,
        filePath: var_filePath,
        fileName: var_fileName,
        mediaType: var_mediaType,
        metadata: var_metadata);
  }

  @protected
  MediaMetadata sse_decode_media_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_timebase = sse_decode_opt_box_autoadd_rational(deserializer);
    var var_audioChannels = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_sampleRate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fileSizeBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    return MediaMetadata(
        width: var_width,
        height: var_height,
        durationPts: var_durationPts,
        durationSeconds: var_durationSeconds,
        timebase: var_timebase,
        audioChannels: var_audioChannels,
        sampleRate: var_sampleRate,
        fileSizeBytes: var_fileSizeBytes);
  }

  @protected
  MediaPool sse_decode_media_pool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_media_item(deserializer);
    return MediaPool(items: var_items);
  }

  @protected
  MediaType sse_decode_media_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaType.values[inner];
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeFrame? sse_decode_opt_box_autoadd_bridge_frame(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_frame(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Rational? sse_decode_opt_box_autoadd_rational(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rational(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_isPlaying = sse_decode_bool(deserializer);
    var var_currentPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_currentSeconds = sse_decode_f_64(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    return PlaybackState(
        sessionId: var_sessionId,
        isPlaying: var_isPlaying,
        currentPts: var_currentPts,
        currentSeconds: var_currentSeconds,
        durationPts: var_durationPts,
        durationSeconds: var_durationSeconds);
  }

  @protected
  PreviewSessionInfo sse_decode_preview_session_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_textureId = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    var var_fps = sse_decode_f_64(deserializer);
    var var_timebase = sse_decode_rational(deserializer);
    return PreviewSessionInfo(
        sessionId: var_sessionId,
        textureId: var_textureId,
        width: var_width,
        height: var_height,
        durationPts: var_durationPts,
        durationSeconds: var_durationSeconds,
        fps: var_fps,
        timebase: var_timebase);
  }

  @protected
  Project sse_decode_project(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_projectPath = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_timeline = sse_decode_timeline(deserializer);
    var var_mediaPool = sse_decode_media_pool(deserializer);
    return Project(
        id: var_id,
        name: var_name,
        projectPath: var_projectPath,
        filePath: var_filePath,
        timeline: var_timeline,
        mediaPool: var_mediaPool);
  }

  @protected
  Rational sse_decode_rational(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_num = sse_decode_i_32(deserializer);
    var var_den = sse_decode_i_32(deserializer);
    return Rational(num: var_num, den: var_den);
  }

  @protected
  Timeline sse_decode_timeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_timebase = sse_decode_rational(deserializer);
    var var_durationPts = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_tracks = sse_decode_list_track(deserializer);
    return Timeline(
        id: var_id,
        timebase: var_timebase,
        durationPts: var_durationPts,
        tracks: var_tracks);
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_Uuid(deserializer);
    var var_kind = sse_decode_track_kind(deserializer);
    var var_clips = sse_decode_list_clip(deserializer);
    return Track(id: var_id, kind: var_kind, clips: var_clips);
  }

  @protected
  TrackKind sse_decode_track_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrackKind.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_StreamSink_bridge_frame_Sse(
      RustStreamSink<BridgeFrame> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_frame,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_playback_state_Sse(
      RustStreamSink<PlaybackState> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_frame(
      BridgeFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_frame(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_item(
      MediaItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_item(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_project(Project self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rational(
      Rational self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rational(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_timeline(
      Timeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_timeline(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_bridge_frame(BridgeFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_CastedPrimitive_i_64(self.pts, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_list_prim_u_8_strict(self.rgbaBytes, serializer);
    sse_encode_u_32(self.rowStrideBytes, serializer);
    sse_encode_f_64(self.timestampSeconds, serializer);
  }

  @protected
  void sse_encode_clip(Clip self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_Uuid(self.sourceId, serializer);
    sse_encode_CastedPrimitive_i_64(self.sourceIn, serializer);
    sse_encode_CastedPrimitive_i_64(self.sourceOut, serializer);
    sse_encode_CastedPrimitive_i_64(self.timelineIn, serializer);
    sse_encode_CastedPrimitive_i_64(self.timelineOut, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_clip(List<Clip> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_clip(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_item(
      List<MediaItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_media_item(MediaItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_media_type(self.mediaType, serializer);
    sse_encode_media_metadata(self.metadata, serializer);
  }

  @protected
  void sse_encode_media_metadata(MediaMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_opt_box_autoadd_rational(self.timebase, serializer);
    sse_encode_opt_box_autoadd_u_16(self.audioChannels, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sampleRate, serializer);
    sse_encode_CastedPrimitive_u_64(self.fileSizeBytes, serializer);
  }

  @protected
  void sse_encode_media_pool(MediaPool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_media_item(self.items, serializer);
  }

  @protected
  void sse_encode_media_type(MediaType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(
      int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_frame(
      BridgeFrame? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_frame(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rational(
      Rational? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rational(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_bool(self.isPlaying, serializer);
    sse_encode_CastedPrimitive_i_64(self.currentPts, serializer);
    sse_encode_f_64(self.currentSeconds, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
  }

  @protected
  void sse_encode_preview_session_info(
      PreviewSessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_CastedPrimitive_i_64(self.textureId, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
    sse_encode_f_64(self.fps, serializer);
    sse_encode_rational(self.timebase, serializer);
  }

  @protected
  void sse_encode_project(Project self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.projectPath, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_timeline(self.timeline, serializer);
    sse_encode_media_pool(self.mediaPool, serializer);
  }

  @protected
  void sse_encode_rational(Rational self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.num, serializer);
    sse_encode_i_32(self.den, serializer);
  }

  @protected
  void sse_encode_timeline(Timeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_rational(self.timebase, serializer);
    sse_encode_CastedPrimitive_i_64(self.durationPts, serializer);
    sse_encode_list_track(self.tracks, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.id, serializer);
    sse_encode_track_kind(self.kind, serializer);
    sse_encode_list_clip(self.clips, serializer);
  }

  @protected
  void sse_encode_track_kind(TrackKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
